name: Auto-approve and merge Dependabot PRs

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        name: Auto-approve PR
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
